Add songs to the play queue
YIO-Remote/integration.spotify pull request #16
Opened 2020-08-11 14:20 UTC by jadlers

Hi,

This PR adds the "Add to queue" command to the list of commands for a single track. In order for this to function I also had to add the `addToQueue` extension to the media player entity in the *YIO-Remote/remote-software* repository. There's a PR open there as well: https://github.com/YIO-Remote/remote-software/pull/497

My first code related contribution and even though it's not a lot of code I'd highly appreciate feedback if there's something that could have been done better!

![2020-08-11_16-12-33](https://user-images.githubusercontent.com/16165462/89908126-d1b12100-dbed-11ea-9a1b-f28bbe467366.png)

2020-08-11 16:41 UTC, zehnm requested changes
Thanks for your contribution! We first have to make it compile :-)

@martonborzak please have a look too, if the queue feature fits the media player. That's more your domain :-)

2020-08-11 16:41 UTC, zehnm commented on src/spotify.cpp
> +    } else if (command == MediaPlayerDef::C_QUEUE) {
This gives a compile error:
```
../src/spotify.cpp:687:43: error: 'C_QUEUE' is not a member of 'MediaPlayerDef'
     } else if (command == MediaPlayerDef::C_QUEUE) {
                                           ^~~~~~~
```
MediaPlayerDef is part of the shared integrations.library project, which in this case also requires a PR

2020-08-12 10:12 UTC, jadlers commented
I've now also created a PR in the `integrations.library` repo. As you (@zehnm) pointed out on Discord I need to change the *dependencies.cfg* file to use the new branch. Is it possible to use my fork or only branches on the main repo are allowed?

2020-08-13 20:48 UTC, martonborzak approved these changes

2020-08-13 21:50 UTC, zehnm commented
> Is it possible to use my fork or only branches on the main repo are allowed?

The required PR of integrations.library is merged and a new release v0.5.1 has been created.
If you pull in the latest integrations.library in your fork, you're good to go.

Required change for this PR: modify dependencies.cfg to include the new release
```
integrations.library: v0.5.1
```
Then the build will work and this PR can be merged 👍

2020-08-17 11:51 UTC, jadlers commented
All done, thanks for the guidance throughout this PR @zehnm !

2020-08-17 20:40 UTC, zehnm approved these changes

2020-08-17 20:41 UTC, merged